import csv
import requests
from bs4 import BeautifulSoup



ESTACIONS = [
  {"nom":"Baqueira/Beret", "link":"https://es.snow-forecast.com/resorts/Baqueira-Beret/snow-report"},
  {"nom":"Boi Taull", "link":"https://es.snow-forecast.com/resorts/Boi-Taull/snow-report"},
  {"nom":"Candanchu", "link":"https://es.snow-forecast.com/resorts/Candanchu/snow-report"},
  {"nom":"Cerler", "link":"https://es.snow-forecast.com/resorts/Cerler/snow-report"},
  {"nom":"Espot Esquí", "link":"https://es.snow-forecast.com/resorts/SuperEspot/snow-report"},
  {"nom":"Formigal", "link":"https://es.snow-forecast.com/resorts/Formigal/snow-report"},
  {"nom":"Fuentes de Invierno", "link":"https://es.snow-forecast.com/resorts/FuentesdeInvierno/snow-report"},
  {"nom":"Javalambre", "link":"https://es.snow-forecast.com/resorts/Javalambre/snow-report"},
  {"nom":"La Molina", "link":"https://es.snow-forecast.com/resorts/La-Molina/snow-report"},
  {"nom":"La-Pinilla", "link":"https://es.snow-forecast.com/resorts/La-Pinilla/snow-report"},
  {"nom":"Larra-Belagua Nordic Ski Cente", "link":"https://es.snow-forecast.com/resorts/Roncalia/snow-report"},
  {"nom":"Leitariegos", "link":"https://es.snow-forecast.com/resorts/Leitariegos/snow-report"},
  {"nom":"Lunada", "link":"https://es.snow-forecast.com/resorts/Lunada/snow-report"},
  {"nom":"Manzaneda", "link":"https://es.snow-forecast.com/resorts/Manzaneda/snow-report"},
  {"nom":"Masella", "link":"https://es.snow-forecast.com/resorts/Masella/snow-report"},
  {"nom":"Panticosa", "link":"https://es.snow-forecast.com/resorts/Panticosa/snow-report"},
  {"nom":"Picos De Europa", "link":"https://es.snow-forecast.com/resorts/Picos-De-Europa/snow-report"},
  {"nom":"Port Del Comte", "link":"https://es.snow-forecast.com/resorts/PortDelComte/snow-report"},
  {"nom":"Port-Ainé", "link":"https://es.snow-forecast.com/resorts/PortAine/snow-report"},
  {"nom":"Puerto de Navacerrada", "link":"https://es.snow-forecast.com/resorts/PuertoDeNavacerrada/snow-report"},
  {"nom":"Puerto de Navafria", "link":"https://es.snow-forecast.com/resorts/Puerto-de-Navafria/snow-report"},
  {"nom":"Pyrenees Heliski", "link":"https://es.snow-forecast.com/resorts/PyreneesHeliski/snow-report"},
  {"nom":"San-Isidro", "link":"https://es.snow-forecast.com/resorts/San-Isidro/snow-report"},
  {"nom":"Sierra de Béjar - La Covatilla", "link":"https://es.snow-forecast.com/resorts/Sierradebejar/snow-report"},
  {"nom":"Sierra Nevada", "link":"https://es.snow-forecast.com/resorts/Sierra-Nevada/snow-report"},
  {"nom":"Tavascan - Pleta del Prat", "link":"https://es.snow-forecast.com/resorts/Tavascan-Pleta-del-Prat/snow-report"},
  {"nom":"Valdelinares", "link":"https://es.snow-forecast.com/resorts/Valdelinares/snow-report"},
  {"nom":"Valdesqui", "link":"https://es.snow-forecast.com/resorts/Valdesqui/snow-report"},
  {"nom":"Valdezcaray", "link":"https://es.snow-forecast.com/resorts/Valdezcaray/snow-report"},
  {"nom":"Valgrande-Pajares", "link":"https://es.snow-forecast.com/resorts/Valgrande-Pajares/snow-report"},
  {"nom":"Vall de Núria", "link":"https://es.snow-forecast.com/resorts/ValldeNuria/snow-report"},
  {"nom":"Vallter 2000", "link":"https://es.snow-forecast.com/resorts/Vallter2000/snow-report"},
  {"nom":"Adelboden","link":"https://es.snow-forecast.com/resorts/Adelboden/snow-report"},
  {"nom":"Aeschi","link":"https://es.snow-forecast.com/resorts/Aeschi/snow-report"},
  {"nom":"Airolo","link":"https://es.snow-forecast.com/resorts/Airolo/snow-report"},
  {"nom":"Alt St. Johann/Toggenburg","link":"https://es.snow-forecast.com/resorts/AltStJohannToggenburg/snow-report"},
  {"nom":"Amden","link":"https://es.snow-forecast.com/resorts/Amden/snow-report"},
  {"nom":"Andermatt","link":"https://es.snow-forecast.com/resorts/Andermatt/snow-report"},
  {"nom":"Anzère","link":"https://es.snow-forecast.com/resorts/Anzere/snow-report"},
  {"nom":"Arolla","link":"https://es.snow-forecast.com/resorts/Arolla/snow-report"},
  {"nom":"Arosa","link":"https://es.snow-forecast.com/resorts/Arosa/snow-report"},
  {"nom":"Atzmännig Goldingen","link":"https://es.snow-forecast.com/resorts/AtzmannigGoldingen/snow-report"},
  {"nom":"Avers","link":"https://es.snow-forecast.com/resorts/Avers/snow-report"},
  {"nom":"Beatenberg","link":"https://es.snow-forecast.com/resorts/Beatenberg/snow-report"},
  {"nom":"Belalp - Blatten - Naters","link":"https://es.snow-forecast.com/resorts/Belalp-Blatten-Naters/snow-report"},
  {"nom":"Bellwald / Goms","link":"https://es.snow-forecast.com/resorts/BellwaldGoms/snow-report"},
  {"nom":"Bergün / Bravuogn","link":"https://es.snow-forecast.com/resorts/BergunBravuogn/snow-report"},
  {"nom":"Bettmeralp - Aletsch","link":"https://es.snow-forecast.com/resorts/Bettmeralp-Aletsch/snow-report"},
  {"nom":"Bivio","link":"https://es.snow-forecast.com/resorts/Bivio/snow-report"},
  {"nom":"Bosco Gurin","link":"https://es.snow-forecast.com/resorts/BoscoGurin/snow-report"},
  {"nom":"Braunwald","link":"https://es.snow-forecast.com/resorts/Braunwald/snow-report"},
  {"nom":"Brienz - Axalp","link":"https://es.snow-forecast.com/resorts/Brienz-Axalp/snow-report"},
  {"nom":"Brigels-Waltensburg-Andiast","link":"https://es.snow-forecast.com/resorts/Brigels-Waltensburg-Andiast/snow-report"},
  {"nom":"Bruson","link":"https://es.snow-forecast.com/resorts/Bruson/snow-report"},
  {"nom":"Bulle - La Chia","link":"https://es.snow-forecast.com/resorts/Bulle-LaChia/snow-report"},
  {"nom":"Bumbach / Schangnau","link":"https://es.snow-forecast.com/resorts/BumbachSchangnau/snow-report"},
  {"nom":"Bürchen - Törbel","link":"https://es.snow-forecast.com/resorts/Burchen-Torbel/snow-report"},
  {"nom":"Celerina/Engadin","link":"https://es.snow-forecast.com/resorts/CelerinaEngadin/snow-report"},
  {"nom":"Champéry","link":"https://es.snow-forecast.com/resorts/Champery/snow-report"},
  {"nom":"Champex-Lac","link":"https://es.snow-forecast.com/resorts/Champex-Lac/snow-report"},
  {"nom":"Champoussin","link":"https://es.snow-forecast.com/resorts/Champoussin/snow-report"},
  {"nom":"Chandolin","link":"https://es.snow-forecast.com/resorts/Chandolin/snow-report"},
  {"nom":"Charmey","link":"https://es.snow-forecast.com/resorts/Charmey/snow-report"},
  {"nom":"Château d'Oex","link":"https://es.snow-forecast.com/resorts/Chateau-d-Oex/snow-report"},
  {"nom":"Chur","link":"https://es.snow-forecast.com/resorts/Chur/snow-report"},
  {"nom":"Churwalden","link":"https://es.snow-forecast.com/resorts/Churwalden/snow-report"},
  {"nom":"Corvatsch-Furtschellas","link":"https://es.snow-forecast.com/resorts/Corvatsch-Furtschellas/snow-report"},
  {"nom":"Corviglia-Marguns","link":"https://es.snow-forecast.com/resorts/Corviglia-Marguns/snow-report"},
  {"nom":"Crans Montana","link":"https://es.snow-forecast.com/resorts/Crans-Montana/snow-report"},
  {"nom":"Dallenwil Wirzweli","link":"https://es.snow-forecast.com/resorts/DallenwilWirzweli/snow-report"},
  {"nom":"Davos","link":"https://es.snow-forecast.com/resorts/Davos/snow-report"},
  {"nom":"Degersheim","link":"https://es.snow-forecast.com/resorts/Degersheim/snow-report"},
  {"nom":"Dent-de-Vaulion","link":"https://es.snow-forecast.com/resorts/Dent-de-Vaulion/snow-report"},
  {"nom":"Diavolezza-Lagalb","link":"https://es.snow-forecast.com/resorts/Diavolezza-Lagalb/snow-report"},
  {"nom":"Diemtigtal - Grimmialp","link":"https://es.snow-forecast.com/resorts/Diemtigtal-Grimmialp/snow-report"},
  {"nom":"Diemtigtal - Springenboden","link":"https://es.snow-forecast.com/resorts/Diemtigtal-Springenboden/snow-report"},
  {"nom":"Diemtigtal - Wiriehorn","link":"https://es.snow-forecast.com/resorts/Diemtigtal-Wiriehorn/snow-report"},
  {"nom":"Disentis","link":"https://es.snow-forecast.com/resorts/Disentis/snow-report"},
  {"nom":"Ebenalp","link":"https://es.snow-forecast.com/resorts/Ebenalp/snow-report"},
  {"nom":"Ebnat-Kappel - Toggenburg","link":"https://es.snow-forecast.com/resorts/Ebnat-Kappel-Toggenburg/snow-report"},
  {"nom":"Eggiwil","link":"https://es.snow-forecast.com/resorts/Eggiwil/snow-report"},
  {"nom":"Eigenthal","link":"https://es.snow-forecast.com/resorts/Eigenthal/snow-report"},
  {"nom":"Einsiedeln","link":"https://es.snow-forecast.com/resorts/Einsiedeln/snow-report"},
  {"nom":"Eischoll","link":"https://es.snow-forecast.com/resorts/Eischoll/snow-report"},
  {"nom":"Elm im Sernftal","link":"https://es.snow-forecast.com/resorts/Elm/snow-report"},
  {"nom":"Emmetten","link":"https://es.snow-forecast.com/resorts/Emmetten/snow-report"},
  {"nom":"Engelberg","link":"https://es.snow-forecast.com/resorts/Engelberg/snow-report"},
  {"nom":"Engstligenalp","link":"https://es.snow-forecast.com/resorts/Engstligenalp/snow-report"},
  {"nom":"Eriz","link":"https://es.snow-forecast.com/resorts/Eriz/snow-report"},
  {"nom":"Ernergalen","link":"https://es.snow-forecast.com/resorts/Ernergalen/snow-report"},
  {"nom":"Evolène","link":"https://es.snow-forecast.com/resorts/Evolene/snow-report"},
  {"nom":"Feldis","link":"https://es.snow-forecast.com/resorts/Feldis/snow-report"},
  {"nom":"Fideris - Fideriser Heuberge","link":"https://es.snow-forecast.com/resorts/Fideris-FideriserHeuberge/snow-report"},
  {"nom":"Fiesch - Eggishorn - Aletsch","link":"https://es.snow-forecast.com/resorts/Fiesch-Eggishorn-Aletsch/snow-report"},
  {"nom":"Flims Laax Falera","link":"https://es.snow-forecast.com/resorts/Flims-Laax/snow-report"},
  {"nom":"Flumserberg","link":"https://es.snow-forecast.com/resorts/Flumserberg/snow-report"},
  {"nom":"Frutigen - Elsigen - Metsch","link":"https://es.snow-forecast.com/resorts/Frutigen-Elsigen-Metsch/snow-report"},
  {"nom":"Giswil - Mörlialp","link":"https://es.snow-forecast.com/resorts/Giswil-Morlialp/snow-report"},
  {"nom":"Gluringen - Goms","link":"https://es.snow-forecast.com/resorts/Gluringen-Goms/snow-report"},
  {"nom":"Goms - Oberwald","link":"https://es.snow-forecast.com/resorts/Goms-Oberwald/snow-report"},
  {"nom":"Grächen","link":"https://es.snow-forecast.com/resorts/Grachen/snow-report"},
  {"nom":"Grimentz","link":"https://es.snow-forecast.com/resorts/Grimentz/snow-report"},
  {"nom":"Grindelwald","link":"https://es.snow-forecast.com/resorts/Grindelwald/snow-report"},
  {"nom":"Grüsch - Danusa","link":"https://es.snow-forecast.com/resorts/Grusch-Danusa/snow-report"},
  {"nom":"Gstaad","link":"https://es.snow-forecast.com/resorts/Gstaad/snow-report"},
  {"nom":"Gstaad - Château-d'Oex","link":"https://es.snow-forecast.com/resorts/Gstaad-Chateau-dOex/snow-report"},
  {"nom":"Gstaad - Saanen - Rougemont","link":"https://es.snow-forecast.com/resorts/Gstaad-Saanen-Rougemont/snow-report"},
  {"nom":"Gstaad - Schönried - Saanenmöser","link":"https://es.snow-forecast.com/resorts/Gstaad-Schonried-Saanenmoser/snow-report"},
  {"nom":"Gstaad - St.Stephan - Zweisimmen","link":"https://es.snow-forecast.com/resorts/Gstaad-StStephan-Zweisimmen/snow-report"},
  {"nom":"Gstaad Glacier 3000","link":"https://es.snow-forecast.com/resorts/GstaadGlacier3000/snow-report"},
  {"nom":"Gstaad/Rinderberg-Saanerslochgrat","link":"https://es.snow-forecast.com/resorts/Gstaad-Rinderberg-Saanerslochgrat/snow-report"},
  {"nom":"Gurnigel","link":"https://es.snow-forecast.com/resorts/Gurnigel/snow-report"},
  {"nom":"Habkern","link":"https://es.snow-forecast.com/resorts/Habkern/snow-report"},
  {"nom":"Haute Nendaz","link":"https://es.snow-forecast.com/resorts/Haute-Nendaz/snow-report"},
  {"nom":"Heiden - Grub - Oberegg Appenzellerland","link":"https://es.snow-forecast.com/resorts/Heiden-Grub-ObereggAppenzellerland/snow-report"},
  {"nom":"Hemberg - Bächli","link":"https://es.snow-forecast.com/resorts/Hemberg-Bachli/snow-report"},
  {"nom":"Hoch-Ybrig","link":"https://es.snow-forecast.com/resorts/Hoch-Ybrig/snow-report"},
  {"nom":"Ibergeregg","link":"https://es.snow-forecast.com/resorts/Ibergeregg/snow-report"},
  {"nom":"Interlaken","link":"https://es.snow-forecast.com/resorts/Interlaken/snow-report"},
  {"nom":"Jaun","link":"https://es.snow-forecast.com/resorts/Jaun/snow-report"},
  {"nom":"Jaunpass - Boltigen","link":"https://es.snow-forecast.com/resorts/Jaunpass-Boltigen/snow-report"},
  {"nom":"Jeizinen","link":"https://es.snow-forecast.com/resorts/Gampel-Jeizinen/snow-report"},
  {"nom":"Kandersteg","link":"https://es.snow-forecast.com/resorts/Kandersteg/snow-report"},
  {"nom":"Kerenzerberg - Filzbach","link":"https://es.snow-forecast.com/resorts/Kerenzerberg-Filzbach/snow-report"},
  {"nom":"Kiental","link":"https://es.snow-forecast.com/resorts/Kiental/snow-report"},
  {"nom":"Klewenalp - Stockhütte","link":"https://es.snow-forecast.com/resorts/Klewenalp-Stockhutte/snow-report"},
  {"nom":"Klosters","link":"https://es.snow-forecast.com/resorts/Klosters/snow-report"},
  {"nom":"Kronberg","link":"https://es.snow-forecast.com/resorts/Kronberg/snow-report"},
  {"nom":"Krummenau - Wolzenalp - Toggenburg","link":"https://es.snow-forecast.com/resorts/Krummenau-Wolzenalp-Toggenburg/snow-report"},
  {"nom":"L'Abbaye / Vallée de Joux","link":"https://es.snow-forecast.com/resorts/LAbbayeValleedeJoux/snow-report"},
  {"nom":"La Berra - La Roche","link":"https://es.snow-forecast.com/resorts/LaBerra-LaRoche/snow-report"},
  {"nom":"La Chaux-de-Fonds","link":"https://es.snow-forecast.com/resorts/La-Chaux-de-Fonds/snow-report"},
  {"nom":"La Corbatière - Vallée de La Sagne","link":"https://es.snow-forecast.com/resorts/La-Corbatiere-Vallee-de-La-Sagne/snow-report"},
  {"nom":"La Dôle","link":"https://es.snow-forecast.com/resorts/LaDole/snow-report"},
  {"nom":"La Forclaz (Evolène)","link":"https://es.snow-forecast.com/resorts/La-Forclaz/snow-report"},
  {"nom":"La Fouly - Val Ferret","link":"https://es.snow-forecast.com/resorts/LaFouly-ValFerret/snow-report"},
  {"nom":"La Punt/Engadin","link":"https://es.snow-forecast.com/resorts/LaPuntEngadin/snow-report"},
  {"nom":"La Tzoumaz","link":"https://es.snow-forecast.com/resorts/LaTzoumaz/snow-report"},
  {"nom":"Langenbruck","link":"https://es.snow-forecast.com/resorts/Langenbruck/snow-report"},
  {"nom":"Lauchernalp - Lötschental","link":"https://es.snow-forecast.com/resorts/Lauchernalp-Lotschental/snow-report"},
  {"nom":"Lauterbrunnen","link":"https://es.snow-forecast.com/resorts/Lauterbrunnen/snow-report"},
  {"nom":"Le Brassus / Vallée de Joux","link":"https://es.snow-forecast.com/resorts/LeBrassusValleedeJoux/snow-report"},
  {"nom":"Le Chable","link":"https://es.snow-forecast.com/resorts/LeChable/snow-report"},
  {"nom":"Le Grand Val","link":"https://es.snow-forecast.com/resorts/LeGrandVal/snow-report"},
  {"nom":"Le Pâquier - Crêt-du-Puy","link":"https://es.snow-forecast.com/resorts/LePaquier/snow-report"},
  {"nom":"Lenk","link":"https://es.snow-forecast.com/resorts/Lenk/snow-report"},
  {"nom":"Lenzerheide","link":"https://es.snow-forecast.com/resorts/Lenzerheide-Valbella/snow-report"},
  {"nom":"Les Breuleux","link":"https://es.snow-forecast.com/resorts/LesBreuleux/snow-report"},
  {"nom":"Les Diablerets","link":"https://es.snow-forecast.com/resorts/Les-Diablerets/snow-report"},
  {"nom":"Les Genevez","link":"https://es.snow-forecast.com/resorts/LesGenevez/snow-report"},
  {"nom":"Les Marécottes - Salvan","link":"https://es.snow-forecast.com/resorts/LesMarecottes-Salvan/snow-report"},
  {"nom":"Les Mosses - La Lécherette","link":"https://es.snow-forecast.com/resorts/LesMosses-LaLecherette/snow-report"},
  {"nom":"Les Paccots","link":"https://es.snow-forecast.com/resorts/Les-Paccots/snow-report"},
  {"nom":"Les Pléiades","link":"https://es.snow-forecast.com/resorts/LesPleiades/snow-report"},
  {"nom":"Les Prés-d'Orvin","link":"https://es.snow-forecast.com/resorts/LesPres-dOrvin/snow-report"},
  {"nom":"Leukerbad","link":"https://es.snow-forecast.com/resorts/Leukerbad/snow-report"},
  {"nom":"Leysin","link":"https://es.snow-forecast.com/resorts/Leysin/snow-report"},
  {"nom":"Lungern-Schönbüel","link":"https://es.snow-forecast.com/resorts/LungernSchonbuel/snow-report"},
  {"nom":"Lungern/Schoenbueel","link":"https://es.snow-forecast.com/resorts/Lungern-Schoenbueel/snow-report"},
  {"nom":"Maloja/Engadin","link":"https://es.snow-forecast.com/resorts/MalojaEngadin/snow-report"},
  {"nom":"Marbach - Marbachegg","link":"https://es.snow-forecast.com/resorts/Marbach-Marbachegg/snow-report"},
  {"nom":"Meiringen-Hasliberg","link":"https://es.snow-forecast.com/resorts/Meiringen/snow-report"},
  {"nom":"Melchsee-Frutt","link":"https://es.snow-forecast.com/resorts/Melchsee-Frutt/snow-report"},
  {"nom":"Moléson s/Gruyères","link":"https://es.snow-forecast.com/resorts/MolesonsGruyeres/snow-report"},
  {"nom":"Mollis - Schilt","link":"https://es.snow-forecast.com/resorts/Mollis-Schilt/snow-report"},
  {"nom":"Monte Tamaro","link":"https://es.snow-forecast.com/resorts/MonteTamaro/snow-report"},
  {"nom":"Morgins","link":"https://es.snow-forecast.com/resorts/Morgins/snow-report"},
  {"nom":"Morgins - Les Portes du Soleil","link":"https://es.snow-forecast.com/resorts/Morgins-LesPortesduSoleil/snow-report"},
  {"nom":"Münster - Geschinen - Goms","link":"https://es.snow-forecast.com/resorts/Munster-Geschinen-Goms/snow-report"},
  {"nom":"Mürren","link":"https://es.snow-forecast.com/resorts/Murren/snow-report"},
  {"nom":"Mythenregion","link":"https://es.snow-forecast.com/resorts/Mythenregion/snow-report"},
  {"nom":"Nara","link":"https://es.snow-forecast.com/resorts/Nara/snow-report"},
  {"nom":"Nax - Mont-Noble","link":"https://es.snow-forecast.com/resorts/Nax-Mont-Noble/snow-report"},
  {"nom":"Nendaz","link":"https://es.snow-forecast.com/resorts/Nendaz/snow-report"},
  {"nom":"Niederrickenbach","link":"https://es.snow-forecast.com/resorts/Niederrickenbach/snow-report"},
  {"nom":"Oberiberg","link":"https://es.snow-forecast.com/resorts/Oberiberg/snow-report"},
  {"nom":"Obersaxen - Mundaun - Val Lumnezia","link":"https://es.snow-forecast.com/resorts/Obersaxen-Mundaun-ValLumnezia/snow-report"},
  {"nom":"Obertoggenburg - Toggenburg","link":"https://es.snow-forecast.com/resorts/Obertoggenburg-Toggenburg/snow-report"},
  {"nom":"Ovronnaz","link":"https://es.snow-forecast.com/resorts/Ovronnaz/snow-report"},
  {"nom":"Pilatus / Luzern","link":"https://es.snow-forecast.com/resorts/Pilatus-Luzern/snow-report"},
  {"nom":"Pizol","link":"https://es.snow-forecast.com/resorts/BadRagaz/snow-report"},
  {"nom":"Pontresina","link":"https://es.snow-forecast.com/resorts/Pontresina/snow-report"},
  {"nom":"Pontresina/Engadin","link":"https://es.snow-forecast.com/resorts/PontresinaEngadin/snow-report"},
  {"nom":"Rathvel s/Châtel-St-Denis","link":"https://es.snow-forecast.com/resorts/RathvelsChatel-St-Denis/snow-report"},
  {"nom":"Reichenbach - Faltschen","link":"https://es.snow-forecast.com/resorts/Reichenbach-Faltschen/snow-report"},
  {"nom":"Ricken","link":"https://es.snow-forecast.com/resorts/Ricken/snow-report"},
  {"nom":"Riederalp - Aletsch","link":"https://es.snow-forecast.com/resorts/Riederalp-Aletsch/snow-report"},
  {"nom":"Riffenmatt","link":"https://es.snow-forecast.com/resorts/Riffenmatt/snow-report"},
  {"nom":"Rigi","link":"https://es.snow-forecast.com/resorts/Rigi/snow-report"},
  {"nom":"Rochers-de-Naye - Caux","link":"https://es.snow-forecast.com/resorts/Rochers-de-Naye-Caux/snow-report"},
  {"nom":"Rossberg Oberwil","link":"https://es.snow-forecast.com/resorts/RossbergOberwiliS/snow-report"},
  {"nom":"Rosswald - Brig","link":"https://es.snow-forecast.com/resorts/Brig-Rosswald/snow-report"},
  {"nom":"Rothenthurm","link":"https://es.snow-forecast.com/resorts/Rothenthurm/snow-report"},
  {"nom":"Rüschegg / Eywald","link":"https://es.snow-forecast.com/resorts/RuscheggEywald/snow-report"},
  {"nom":"Saas Almagell","link":"https://es.snow-forecast.com/resorts/SaasAlmagell/snow-report"},
  {"nom":"Saas Grund","link":"https://es.snow-forecast.com/resorts/SaasGrund/snow-report"},
  {"nom":"Samedan/Engadin","link":"https://es.snow-forecast.com/resorts/SamedanEngadin/snow-report"},
  {"nom":"Samnaun","link":"https://es.snow-forecast.com/resorts/Samnaun/snow-report"},
  {"nom":"San Bernardino","link":"https://es.snow-forecast.com/resorts/SanBernardino/snow-report"},
  {"nom":"Sarn - Heinzenberg","link":"https://es.snow-forecast.com/resorts/Sarn-Heinzenberg/snow-report"},
  {"nom":"Sattel - Hochstuckli","link":"https://es.snow-forecast.com/resorts/Sattel-Hochstuckli/snow-report"},
  {"nom":"Savagnières - Bugnenets","link":"https://es.snow-forecast.com/resorts/Savagnieres-Bugnenets/snow-report"},
  {"nom":"Savognin","link":"https://es.snow-forecast.com/resorts/Savognin/snow-report"},
  {"nom":"Schwägalp - Appenzellerland","link":"https://es.snow-forecast.com/resorts/Schwagalp-Appenzellerland/snow-report"},
  {"nom":"Schwanden - Sigriswil","link":"https://es.snow-forecast.com/resorts/Schwanden-Sigriswil/snow-report"},
  {"nom":"Schwarzsee","link":"https://es.snow-forecast.com/resorts/Schwarzsee/snow-report"},
  {"nom":"Schwefelberg-Bad","link":"https://es.snow-forecast.com/resorts/Schwefelberg-Bad/snow-report"},
  {"nom":"Schwellbrunn - Appenzellerland","link":"https://es.snow-forecast.com/resorts/Schwellbrunn-Appenzellerland/snow-report"},
  {"nom":"Scuol/Engadin","link":"https://es.snow-forecast.com/resorts/ScuolEngadin/snow-report"},
  {"nom":"Sedrun Oberalp","link":"https://es.snow-forecast.com/resorts/SedrunOberalp/snow-report"},
  {"nom":"Sessel-Gommiswald","link":"https://es.snow-forecast.com/resorts/SesselGommiswald/snow-report"},
  {"nom":"Sils/Engadin","link":"https://es.snow-forecast.com/resorts/SilsEngadin/snow-report"},
  {"nom":"Silvaplana/Engadin","link":"https://es.snow-forecast.com/resorts/SilvaplanaEngadin/snow-report"},
  {"nom":"Skilift Oberholz – Farner","link":"https://es.snow-forecast.com/resorts/Oberholz-Farner/snow-report"},
  {"nom":"Sörenberg","link":"https://es.snow-forecast.com/resorts/Sorenberg/snow-report"},
  {"nom":"Splügen","link":"https://es.snow-forecast.com/resorts/Splugen/snow-report"},
  {"nom":"St Moritz","link":"https://es.snow-forecast.com/resorts/St-Moritz/snow-report"},
  {"nom":"St-Cergue - La Dôle","link":"https://es.snow-forecast.com/resorts/St-Cergue-LaDole/snow-report"},
  {"nom":"St-Luc","link":"https://es.snow-forecast.com/resorts/St-Luc/snow-report"},
  {"nom":"St. Antönien","link":"https://es.snow-forecast.com/resorts/StAntonien/snow-report"},
  {"nom":"St. Peter - Pagig","link":"https://es.snow-forecast.com/resorts/StPeter-Pagig/snow-report"},
  {"nom":"Staldenried - Gspon","link":"https://es.snow-forecast.com/resorts/Staldenried-Gspon/snow-report"},
  {"nom":"Ste-Croix / Les Rasses","link":"https://es.snow-forecast.com/resorts/Ste-CroixLesRasses/snow-report"},
  {"nom":"Steg im Tösstal","link":"https://es.snow-forecast.com/resorts/Steg-im-Tosstal/snow-report"},
  {"nom":"Stoos","link":"https://es.snow-forecast.com/resorts/Stoos/snow-report"},
  {"nom":"Thusis - Tschappina - Urmein","link":"https://es.snow-forecast.com/resorts/Thusis-Tschappina-Urmein/snow-report"},
  {"nom":"Thyon-Printze","link":"https://es.snow-forecast.com/resorts/Thyon-Printze/snow-report"},
  {"nom":"Torgon-Les Portes du Soleil","link":"https://es.snow-forecast.com/resorts/Torgon-LesPortesduSoleil/snow-report"},
  {"nom":"Tramelan et Région","link":"https://es.snow-forecast.com/resorts/TramelanetRegion/snow-report"},
  {"nom":"Trogen - Appenzellerland","link":"https://es.snow-forecast.com/resorts/Trogen-Appenzellerland/snow-report"},
  {"nom":"Tschiertschen","link":"https://es.snow-forecast.com/resorts/Tschiertschen/snow-report"},
  {"nom":"Unterbäch","link":"https://es.snow-forecast.com/resorts/Unterbach/snow-report"},
  {"nom":"Unterwasser - Toggenburg","link":"https://es.snow-forecast.com/resorts/Unterwasser-Toggenburg/snow-report"},
  {"nom":"Urnäsch","link":"https://es.snow-forecast.com/resorts/Urnasch/snow-report"},
  {"nom":"Urnerboden","link":"https://es.snow-forecast.com/resorts/Urnerboden/snow-report"},
  {"nom":"Val Müstair","link":"https://es.snow-forecast.com/resorts/ValMustair/snow-report"},
  {"nom":"Val-de-Travers / La Robella","link":"https://es.snow-forecast.com/resorts/Val-de-TraversLaRobella/snow-report"},
  {"nom":"Vallée de Joux","link":"https://es.snow-forecast.com/resorts/ValleedeJoux/snow-report"},
  {"nom":"Vals","link":"https://es.snow-forecast.com/resorts/Vals/snow-report"},
  {"nom":"Verbier","link":"https://es.snow-forecast.com/resorts/Verbier/snow-report"},
  {"nom":"Vercorin","link":"https://es.snow-forecast.com/resorts/Vercorin/snow-report"},
  {"nom":"Veysonnaz-Printse","link":"https://es.snow-forecast.com/resorts/Veysonnaz-Printze/snow-report"},
  {"nom":"Vichères-Liddes","link":"https://es.snow-forecast.com/resorts/Vicheres-Liddes/snow-report"},
  {"nom":"Villars","link":"https://es.snow-forecast.com/resorts/Villars/snow-report"},
  {"nom":"Visperterminen","link":"https://es.snow-forecast.com/resorts/Visperterminen/snow-report"},
  {"nom":"Vue des Alpes - Tête de Ran","link":"https://es.snow-forecast.com/resorts/VuedesAlpes-Tetederan/snow-report"},
  {"nom":"Weissenstein-Solothurn-Balmberg","link":"https://es.snow-forecast.com/resorts/WeissensteinSolothurnBalmberg/snow-report"},
  {"nom":"Wengen","link":"https://es.snow-forecast.com/resorts/Wengen/snow-report"},
  {"nom":"Wilderswil","link":"https://es.snow-forecast.com/resorts/Wilderswil/snow-report"},
  {"nom":"Wildhaus - Toggenburg","link":"https://es.snow-forecast.com/resorts/Wildhaus-Toggenburg/snow-report"},
  {"nom":"Zermatt","link":"https://es.snow-forecast.com/resorts/Zermatt/snow-report"},
  {"nom":"Zernez","link":"https://es.snow-forecast.com/resorts/Zernez/snow-report"},
  {"nom":"Zinal","link":"https://es.snow-forecast.com/resorts/Zinal/snow-report"}]  
def get_info(estacio):
    data = {}
    data["nom"] = estacio["nom"]
    data["link"] = estacio["link"]
    page = requests.get(estacio["link"])
    print("Scrappejant la web...")
    #print(page)

    soup = BeautifulSoup(page.content, 'html.parser')
    print("Fresh snow:")
    nevades = soup.find('span', class_='snow').get_text()
    data["nevades"] = nevades
    print(nevades)

    estado = soup.find('td', class_='value resort-runs').get_text()
    data["estado"] = estado
    print("Estat de les pistes:")
    print(estado)

    dataReport = soup.find('nobr').get_text()
    data["dataReport"] = dataReport
    #report = soup.find_all('span',class_="report-key").parent
    #print(report)
    neuPista = soup.find('td', class_='value on-piste').get_text()
    data["neuPista"] = neuPista
    nevades=soup.find_all('div', class_='outer')
    maximNevada = nevades[1].get_text()
    minimNevada = nevades[0].get_text()
    data["maximNevada"] = maximNevada
    data["minimNevada"] = minimNevada

    return data


list_data = []
for estacio in ESTACIONS:
    data = get_info(estacio)
    list_data.append(data)
print(list_data)

with open('csvEstadoNive.csv', 'w') as f:
    myFields = ['nom', 'link', 'nevades','dataReport','neuPista','estado', 'maximNevada', 'minimNevada']
    writer = csv.DictWriter(f, fieldnames=myFields)
    writer.writeheader()
    for data in list_data:
        writer.writerow(data)

print("DONE")



